### ISSUE TITLE
get value from deep nested json

### ISSUE THREAD

**Issue by simranpal07** [joedski/musings#170]
Hi Joe,
Hope you are doing good. I am currently stuck on one problem, I have the solution but I feel you can give me better solution for the same.

I have a JSON obj and want to access the deep nested property from that, for example: -

response = {
  "key": "val1",
  "key2": [
    {
      "innerKey1": {
        "in1": "someValue",
        "innerArr": [
          {
            "needThisAtt": {
              "foo": "bar"
            }
          }
        ]
      }
    }
  ]
}

Now I want to get `needThisAtt` from the json, I know we can do traversing by using `.` and `[]`,  object destruction and recursion to find the attribute.
 Any suggestion from your side.

**Comment by joedski** [comment]
Hey Simran, terribly sorry about the late response, I was staying off of most online things for a time.  I hope things are still going well for you.

As for this example here, there's nothing better I can think of besides just directly accessing it:

```js
response = {
  key: "val1",
  key2: [
    {
      innerKey1: {
        in1: "someValue",
        innerArr: [
          {
            needThisAtt: {
              foo: "bar",
            },
          },
        ],
      },
    },
  ],
};

const directlyAccess = response.key2[0].innerKey1.innerArr[0].needThisAtt;
```

That of course assumes the desired element is the first one in each array.

If you needed to actually find by certain conditions, you can use the new [optional-chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining):

```js
const maybeAccess = response.key2.find(elem => elem.innerKey1.in1 === "someValue")?.innerKey1.innerArr.find(elem => elem.needThisAtt.foo === "bar")?.needThisAtt;

// Or if we break this across lines...
const maybeAccess =
  response.key2
    .find(elem => elem.innerKey1.in1 === "someValue")
    ?.innerKey1
    .innerArr
    .find(elem => elem.needThisAtt.foo === "bar")
    ?.needThisAtt;
```

However, like any other way to do this, it's going to depend on the exact situation.

**Comment by simranpal07** [comment]
Thank you very much Joe.
